version: '3.8'

services:
  player:
    build:
      context: ./player
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - server
    environment:
      - VITE_API_BASE_URL=http://localhost:3000
      - VITE_WS_BASE_URL=ws://localhost:3000

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DB_DIALECT=sqlite
      - DB_STORAGE=/data/sync-player.sqlite
      - LOG_LEVEL=info
    volumes:
      - ./data:/data

volumes:
  data: 